apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx      # Selects the pods with this label
  ports:
  - port: 80          # The port that the service will expose inside the cluster
    targetPort: 80     # The port on the pod that the service will forward traffic to
    nodePort: 30007    # The port exposed on each node (use a port in the range 30000-32767)

lets try to check git pull
